# Generated by Django 4.0 on 2022-07-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_Category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shef_id', models.IntegerField(max_length=5)),
                ('shef_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_Name', models.CharField(max_length=30)),
                ('Dish_Image', models.ImageField(upload_to='')),
                ('Dish_Price', models.IntegerField()),
                ('Dish_SubCategory', models.CharField(max_length=60, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
        ),
    ]
