# Generated by Django 4.0 on 2022-07-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shef',
            name='shef_id',
            field=models.IntegerField(),
        ),
    ]
