# Generated by Django 4.0 on 2022-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_shef_shef_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Dish_Image',
            field=models.ImageField(upload_to='DishesImage/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Dish_SubCategory',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
